### ISSUE TITLE
Change local csv file location

### ISSUE THREAD

**Issue by gabrielmocan** [wait4signal/sharing-is-caring#6]
Hello, it is possible to create a input parameter to change default local csv location `*/Terminal\Common\Files\Sharing-Is-Caring[providerAccount]-positions.csv` to anything else?

I want to share a volume between containers that runs MT5, one will be master other will be slave. That's why I would like to be able to change this parameter.

Best,
Gabe.

**Comment by bgabela** [comment]
This config was not exposed to minimise number of configs for user. I will expose it next time I make updates.
However, in the meantime you could create a symlink to point this path wherever you want.

**Comment by gabrielmocan** [comment]
@bgabela thanks, yeah I managed to do it by exposing the folder as a volume, still, it would be nice to be able to change it.

**Comment by venomdev** [comment]
I don't think MetaTrader EAs can write to files outside of the Common\Files directory, it's a hard limitation of the language. 

Probably a built in safety feature.

**Comment by bgabela** [comment]
Checked it, venomdev was right...it does not work with paths outside of mt5 files directory
